version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: hospedaya-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"        # opcional, para conectarte desde tu host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospedayaadmin -d hospedaya"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: hospedaya-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Perfil de Spring
      SPRING_PROFILES_ACTIVE: prod

      # Config DB para application-prod.properties
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      # Env de negocio (negocio/infra)
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      MP_SUCCESS_URL: ${MP_SUCCESS_URL}
      MP_PENDING_URL: ${MP_PENDING_URL}
      MP_FAILURE_URL: ${MP_FAILURE_URL}
      MP_WEBHOOK_URL: ${MP_WEBHOOK_URL}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER: ${CLOUDINARY_FOLDER}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL} # backend visto desde frontend en Docker
    ports:
      - "8080:8080"

  frontend:
    build: ./hospedaya-frontend
    container_name: hospedaya-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres_data:
